### ISSUE TITLE
可以请教下您这边在dense_features的设置上有尝试过一些原始特征/处理后特征的方式吗？

### ISSUE THREAD

**Issue by BovenPeng** [ouc16020021031/video-click-TOP1#1]
`dense_features = []`
我看您在代码上没考虑任何特征作为`dense_features`，请问您在这上面有做过一些尝试吗？
是出于什么原因而考虑这样操作的？
谢谢您了。

**Comment by ouc16020021031** [comment]
太久了，不记得了，应该是因为数据基本都是类别特征吧，我们在取得较高成绩后并没有继续深入

**Comment by BovenPeng** [comment]
还有个问题，能请教下您吗？
为什么这里二分类问题用`multi_category_focal_loss2`, 而不是`binary_focal_loss`。

**Comment by ouc16020021031** [comment]
focal_loss是队友后来加的，我觉得应该没有什么特别的理由，用哪个都行

**Comment by BovenPeng** [comment]
好的，谢谢您的解答！
