### ISSUE TITLE
lstm的序列特征

### ISSUE THREAD

**Issue by chen849157649** [ouc16020021031/video-click-TOP1#3]
![微信截图_20200709171058](https://user-images.githubusercontent.com/32058220/87021004-38b27300-c207-11ea-976e-f9ba4486b9e5.png)
你好，感谢你的开源，我想问的是如果使用这个模型训练后，在线推理，输入的是每个用户的一条record, 想构造序列特征的话就去查到之前用户的记录record，否则模型就没法在线预测了，是这样吗？

**Comment by ouc16020021031** [comment]
这个模型时空穿越了，用到了用户之后的信息，实际应用你得改改

**Comment by chen849157649** [comment]
> 这个模型时空穿越了，用到了用户之后的信息，实际应用你得改改

@ouc16020021031 , 你时间戳gap，每个deviceid当前视频曝光时间与上一次视频曝光时间的时间间隔，并对其进行log平滑，是当前减上一次，并没有用户之后的信息呀，你指的是哪块？

**Comment by ouc16020021031** [comment]
有的，你自己算算我这个循环的i-l的值，从正到负，用了前后的信息

**Comment by chen849157649** [comment]
> 有的，你自己算算我这个循环的i-l的值，从正到负，用了前后的信息

@ouc16020021031 ,找到了，将2*L+1改为L，只使用当前点击之前的gap就行，另外我想问下，训练模型的是对数据集做了一些其他方面的特征工程，比如离散化，历史曝光点击统计(均值，方差等)，在模型预测的时候对方请求来的数据只有几条，这种情况怎么做呢？

**Comment by ouc16020021031** [comment]
你看下冷启动吧
